import { useEffect, useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import App from '../App'
import { getContent, listContents, listTaxonomy, type Category, type UnifiedContent } from '../api'
import { isAdmin } from '../auth'
import ReadingProgress from '../components/ReadingProgress'
import { ReadingFooter } from './JournalHub'

export default function LifeHub() {
  const params = new URLSearchParams(window.location.search), requestedId = Number(params.get('id')), legacyType = params.get('type'), returnFilter = params.get('from')
  const [entries,setEntries]=useState<UnifiedContent[]>([]), [categories,setCategories]=useState<Category[]>([]), [filter,setFilter]=useState(params.get('filter')||'all'), [detail,setDetail]=useState<UnifiedContent|null>(null), [loading,setLoading]=useState(true), [query,setQuery]=useState('')
  useEffect(()=>{ if(requestedId){const all=listContents('life');Promise.all([legacyType?all.then(({contents})=>{const match=contents.find((item)=>item.legacy_type===legacyType&&item.legacy_id===requestedId);if(!match)throw new Error('not found');return getContent(match.id)}):getContent(requestedId),all]).then(([{content},{contents}])=>{setDetail(content);setEntries(contents)}).finally(()=>setLoading(false));return} Promise.all([listContents('life'),listTaxonomy()]).then(([data,taxonomy])=>{setEntries(data.contents);setCategories(taxonomy.channels.find((channel)=>channel.id==='life')?.categories||[])}).finally(()=>setLoading(false))},[])
  const visible=useMemo(()=>{const keyword=query.trim().toLowerCase();return entries.filter((entry)=>(filter==='all'||(filter==='none'?entry.category_id===null:entry.category_id===Number(filter)))&&(!keyword||`${entry.title} ${entry.body} ${entry.subtitle||''}`.toLowerCase().includes(keyword)))},[entries,filter,query])
  if(requestedId)return <App><LifeDetail item={detail} entries={entries} loading={loading} returnFilter={returnFilter}/></App>
  return <App><main className="hub-page"><header className="hub-hero life-hero"><a href="/" className="hub-back">← LongTeng.</a><p>/ LIFE ARCHIVE</p><h1>生活分享<span>。</span></h1><div className="hub-hero-copy"><p>旅行、收藏和零碎日常。技术之外，也认真收藏生活。</p><strong>{entries.length||'—'} 个片段</strong></div></header>
    <div className="hub-toolbar" role="group" aria-label="生活内容筛选"><button onClick={()=>setFilter('all')} className={filter==='all'?'active':''}>全部</button>{categories.map((category)=><button key={category.id} onClick={()=>setFilter(String(category.id))} className={filter===String(category.id)?'active':''}>{category.name}</button>)}<button onClick={()=>setFilter('none')} className={filter==='none'?'active':''}>其他</button>{isAdmin()&&<div className="ml-auto text-xs"><a href="/admin.html">进入管理中心</a></div>}</div>
    <label className="hub-search"><span>搜索</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索生活片段…"/>{query&&<button onClick={()=>setQuery('')}>×</button>}</label>
    {loading&&<p className="hub-empty">正在整理生活片段…</p>}{!loading&&!visible.length&&<p className="hub-empty">这个分类暂时还没有内容。</p>}<section className="life-grid">{visible.map((entry,index)=><a key={entry.id} href={`/life.html?id=${entry.id}&from=${filter}`} className={['life-card',index===0?'featured':'','focus-ring'].join(' ')}><div className="life-media">{entry.images[0]?<img src={entry.images[0]} alt="" loading="lazy"/>:<div className="life-placeholder note"><span>MOMENT</span></div>}</div><div className="life-card-copy"><div><span>{entry.category_name||'其他'}{entry.subtitle?` · ${entry.subtitle}`:''}</span><time>{entry.date}</time></div><h2>{entry.title}</h2><p>{entry.body.slice(0,110)}</p></div></a>)}</section>
  </main></App>
}
function LifeDetail({item,entries,loading,returnFilter}:{item:UnifiedContent|null;entries:UnifiedContent[];loading:boolean;returnFilter:string|null}){const back=returnFilter?`/life.html?filter=${encodeURIComponent(returnFilter)}`:'/life.html';useEffect(()=>{if(!item)return;const description=(item.subtitle||item.body).replace(/[#*`>\n]/g,' ').trim().slice(0,150);document.title=`${item.title} · LongTeng`;document.querySelector('meta[name="description"]')?.setAttribute('content',description);const script=document.createElement('script');script.type='application/ld+json';script.text=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:item.title,description,author:{'@type':'Person',name:'LongTeng'},dateModified:new Date(item.updated_at*1000).toISOString(),mainEntityOfPage:window.location.href});document.head.appendChild(script);return()=>{document.title='生活分享 · LongTeng';script.remove()}},[item]);if(loading)return <main className="hub-page"><p className="hub-empty">正在打开生活片段…</p></main>;if(!item)return <main className="hub-page"><a href={back} className="hub-back">← 返回生活分享</a><p className="hub-empty">没有找到这条内容。</p></main>;const peers=entries.filter((entry)=>entry.id!==item.id&&entry.category_id===item.category_id).slice(0,3),index=entries.findIndex((entry)=>entry.id===item.id),previous=entries[index+1],next=index>0?entries[index-1]:null;return <main className="hub-page reading-page life-reading"><ReadingProgress/><a href={back} className="hub-back">← 返回生活分享</a><header className="reading-header"><span className="kind-pill">{item.category_name||'其他'}</span><h1>{item.title}</h1><div><time>{item.date}</time>{item.subtitle&&<span>{item.subtitle}</span>}</div></header>{item.images.length>0&&<div className="life-detail-images">{item.images.map((src,index)=><img key={src} src={src} alt={`${item.title} ${index+1}`} loading={index===0?'eager':'lazy'}/>)}</div>}<article className="reading-body"><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.body}</ReactMarkdown></article><ReadingFooter channel="life" previous={previous} next={next} peers={peers}/></main>}
